### ISSUE TITLE
Update Ansible development tools documentation

### ISSUE THREAD

**Issue by llennoccm** [ansible/ansible-dev-tools#149]
This documentation article refers to "Ansible development tools" as "ADT" which is not approved under Red Hat brand guidelines. 

Only "Ansible development tools" is allowed (see row 156 in this spreadsheet: https://docs.google.com/spreadsheets/d/1DLS_lS3VKidgZIvcLmLp9BoiqptkvqHWfe1D5FD2kfk/edit#gid=1375785039)

Please remove the use of ADT through this doc.

thanks!

**Comment by ssbarnea** [comment]
Please note that "adt" is the command line command and the acronym of the tool name. We can clearly avoid use of of in many places but I do not think that a total removal is feasible.
