### ISSUE TITLE
pipx support

### ISSUE THREAD

**Issue by jmg-duarte** [ansible/ansible-dev-tools#199]
Hello! I use Python with pyenv, so that I can switch among versions when necessary, this means that my pip installs are not "permanent" and as such, if I install ansible-dev-tools with `pip` I'll need to jump around versions or duplicate installs.

If I try using pipx with `pipx install ansible-dev-tools`, `adt` becomes available but not `ansible-lint` and its friends.

Support for `pipx` would be great to isolate the tool from the installation itself.

**Comment by ssbarnea** [comment]
Plase read the pipx documentation, look for `--include-deps` flag when installing it, should do what you want.

There is nothing we can do on our side about this one.

**Comment by armpogart** [comment]
Leaving actual `pipx` command needed here for future users reference:
```sh
pipx inject --include-deps ansible ansible-dev-tools
```
