### ISSUE TITLE
Support specifying specific ansible version

### ISSUE THREAD

**Issue by jedthe3rd** [ansible/ansible-dev-tools#314]
I really love the path this repo is taking things. One requirement that I deal with in our Ansible environment is needing to develop for specific versions of ansible. It would be great if we could install ansible-dev-tools (and better yet just have the devcontainers built) targeting a specific ansible-core version. I would think only major versions are needed for my use case but being able to target minor would be useful as well.

**Comment by ssbarnea** [comment]
I am closing this ticket as this is an unlikely use-case and no is expected.
