### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by trishnaguha** [ansible/ansible-dev-tools#36]
Ansible Developer Tools (brief - this is the documentation home page)

- [x] (highlight) Single point for installation
- [x] (highlight) Combination of tools vetted and used by previous content authors
- [x] (highlight) The SDK reflects the tools used by certified and validated content developers
- [x] (highlight) Introduces tools that a developer may be less familiar with
- [x] (tools - what and how they are used together and for what purpose)
- [ ] (author) 1-2 paragraphs for each tool highlighting key functionality, can probably be harvested from existing READMEs and dos. 
- [x] Identify how each tool is valuable during local interactive development, local testing. and then in a CI pipeline (linting and testing)
- [x] (highlight) Same tools and outcomes locally and in CI
- [x] (note) include the extension in the enumeration of the tools. Although it is not packaged with the python of rpm pkg, it is an integral part of the experience

**Comment by ssbarnea** [comment]
I am closing thing as done as they are mostly done. If future updates are needed, just mention this ticket.
