### ISSUE TITLE
Implement devcontainers feature paradigm for ansible-dev-tools devspaces container

### ISSUE THREAD

**Issue by jedthe3rd** [ansible/ansible-dev-tools#380]
I am currently implementing dev-tools containers for our development. Is there a plan to implement a feature distribution for ansible-dev-tools? How your current example is defined doesn't really follow the features paradigm that the devcontainers standard is driving toward. I wasn't sure if that was intentional or not.

Reference -
https://containers.dev/implementors/features-distribution/

**Comment by ssbarnea** [comment]
Feel free to make a PR to implement it. We have nothing against it but is not on our roadmap.
