### ISSUE TITLE
Creating collections of automation content

### ISSUE THREAD

**Issue by trishnaguha** [ansible/ansible-dev-tools#39]
Creating collections of automation content

- Scaffold with creator
- ade (pip4a) to install it editable with python deps in a venv
- Lint
- Navigator

**Comment by priyamsahoo** [comment]
Mostly, this is similar to https://github.com/ansible/ansible-dev-tools/issues/46.

I have created a README file in the repository under my name with the docs for `using various Ansible developer tools in a unified way.` The doc has the written content, images, and gifs for the documentation. Content can be migrated from here once the initial framework for the documentation is ready.
It is available here: https://github.com/priyamsahoo/ansible-development-ecosystem-doc/blob/main/README.md

**Comment by Qalthos** [comment]
Use https://github.com/ansible/ansible-dev-tools/issues/46 instead
