### ISSUE TITLE
Bootstrap a new collection

### ISSUE THREAD

**Issue by trishnaguha** [ansible/ansible-dev-tools#46]
This will live in the **User Guide** page.
**Bootstrap a new collection**
Use of creator to scaffold, ade (pip4a) to install it editable with python deps in a venv, use the extension with lint to author, playbook or navigator to run

**Comment by trishnaguha** [comment]
Looks like this was closed by Getting started guide. 
https://ansible.readthedocs.io/projects/dev-tools/getting-started/ needs to be filled by this content

**Comment by ssbarnea** [comment]
Closing because https://ansible.readthedocs.io/projects/dev-tools/user-guide/building-collection/ is coving it.
