### ISSUE TITLE
Publish on conda-forge?

### ISSUE THREAD

**Issue by Hoeze** [ansible/ansible-dev-tools#491]
##### ISSUE TYPE

- Feature Idea

##### SUMMARY

Hi, since `ansible` is already available on `conda-forge`, I was wondering whether this package could also be published within conda-forge.
Ref.:
- https://anaconda.org/conda-forge/ansible
- https://github.com/conda-forge/ansible-feedstock

**Comment by jcox10** [comment]
Here is the documentation of the process: https://conda-forge.org/docs/maintainer/adding_pkgs/
Anyone can add packages to conda-forge, for example I have added a package that I really have no involvement in. The process isn't too difficult, but it takes some time to get through all the steps. Once it is published, they have bots that watch pypi and automatically open PRs to publish into conda-forge, so maintenance is pretty easy.

**Comment by ssbarnea** [comment]
I will close this as wontfix because our team will not be able to work on it in the foreseeable future. Still, keep in mind that we will consider PRs that make the publication there easier for those downstream repackagers.
