### ISSUE TITLE
Installation page missing Creator

### ISSUE THREAD

**Issue by trishnaguha** [ansible/ansible-dev-tools#84]
Creator tool is missing in the ~**Installation** page https://ansible.readthedocs.io/projects/dev-tools/installation/#usage-design-review~. 
Missing in the **Included packages** list  https://ansible.readthedocs.io/projects/dev-tools/#included-packages

**Comment by trishnaguha** [comment]
cc @ssbarnea 
I have assigned this to Cristiano as he wrote the installation guide.

**Comment by cristianonicolai** [comment]
@trishnaguha I can see `ansible-creator` in the list, am I missing something?

**Comment by cristianonicolai** [comment]
ok, I think I found the issue, it got moved to another page.

**Comment by trishnaguha** [comment]
My mistake, this is where the package is missing https://ansible.readthedocs.io/projects/dev-tools/#included-packages
